 variables:
     DOCKER_DRIVER: overlay2
     DOCKER_TLS_CERTDIR: ""
     VERSION: "latest"
     NAME: "petclinic"


 stages:
     - sonar

 sonar:
     stage: sonar
     image: maven:3.6.3-jdk-11-slim
     variables:
          SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
          GIT_DEPTH: "0"
     cache:
         key: "${CI_JOB_NAME}"
         paths:
             - .sonar/cache
     script:
         - mvn -T1C verify sonar:sonar -Dsonar.projectKey=seba8co_jgsu-spring-petclinic_AX7aPA6L1SJJQzUufuKs
     allow_failure: true
     artifacts:
         paths:
             - target/*.jar
